name = "mainweb"
main = "src/index.js"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[[kv_namespaces]]
binding = "BOARD_KV"
id = "50d67357af744b47a142555b10eeb2cd"
